name: Build and Deploy

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: cr.yandex/${{ secrets.REGISTRY_ID }}
  IMAGE_NAME: netology-devops-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Yandex Container Registry
        run: |
          # Установка yc CLI
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /usr/local -n
          export PATH=$PATH:/usr/local/bin
          
          # Аутентификация
          echo '${{ secrets.YC_SA_KEY }}' > sa_key.json
          yc config set service-account-key sa_key.json
          yc container registry configure-docker --registry-id ${{ secrets.REGISTRY_ID }}
          
          # Логин в Docker
          cat sa_key.json | docker login --username json_key --password-stdin cr.yandex

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Set tag for tagged releases
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG

  deploy:
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo '${{ secrets.KUBE_CONFIG }}' > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          kubectl set image deployment/netology-app netology-app=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG
          kubectl rollout status deployment/netology-app
